apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-deployment-1"
  namespace: "default"
  labels:
    app: "my-deployment-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "my-deployment-1"
  template:
    metadata:
      labels:
        app: "my-deployment-1"
    spec:
      containers:
        - name: "app1"
          image: "us-central1-docker.pkg.dev/dbms-lab-414417/microservice1/service1:latest"
          volumeMounts:
            - name: shared-data
              mountPath: /judith_PV_dir
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: pvc-new

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: default
spec:
  selector:
    app: my-deployment-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer